language: objective-c
osx_image: xcode8
script: xcodebuild clean test -project VBPieChart.xcodeproj  -scheme VBPieChart -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'
